version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app-image
    container_name: node-app-container
    ports:
      - "49160:8080"
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network

networks:
  node-network:
